# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_20

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_20"
  value = {
    framework   = "GDPR"
    code        = "Art_20"
    title       = <<-SW360_TITLE_gdpr_art_20
GDPR Article 20 — Right to data portability
SW360_TITLE_gdpr_art_20
    description = <<-SW360_BODY_gdpr_art_20
Catalog control Art_20. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_20
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
