# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug ccpa_1798_100

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CCPA 1798.100"
  value = {
    framework   = "CCPA"
    code        = "1798.100"
    title       = <<-SW360_TITLE_ccpa_1798_100
CCPA 1798.100 — Consumer right to know categories and specific pieces of PI
SW360_TITLE_ccpa_1798_100
    description = <<-SW360_BODY_ccpa_1798_100
Catalog control 1798.100. Map evidence collection, ownership, and automation to organizational policy. Framework: California Consumer Privacy Act — selected Civil Code sections.
SW360_BODY_ccpa_1798_100
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
