# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_bai09

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT BAI09"
  value = {
    framework   = "COBIT"
    code        = "BAI09"
    title       = <<-SW360_TITLE_cobit_bai09
COBIT 2019 — BAI09 Managed assets
SW360_TITLE_cobit_bai09
    description = <<-SW360_BODY_cobit_bai09
Catalog control BAI09. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_bai09
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
