# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug hipaa_164_308_a_1_ii_c

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "HIPAA 164.308(a)(1)(ii)(C)"
  value = {
    framework   = "HIPAA"
    code        = "164.308(a)(1)(ii)(C)"
    title       = <<-SW360_TITLE_hipaa_164_308_a_1_ii_c
HIPAA Security Rule 164.308(a)(1)(ii)(C) — Sanction policy
SW360_TITLE_hipaa_164_308_a_1_ii_c
    description = <<-SW360_BODY_hipaa_164_308_a_1_ii_c
Catalog control 164.308(a)(1)(ii)(C). Map evidence collection, ownership, and automation to organizational policy. Framework: HIPAA Security Rule (45 CFR Part 164 Subpart C).
SW360_BODY_hipaa_164_308_a_1_ii_c
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
