# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug iso27001_a_5_10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "ISO27001 A.5.10"
  value = {
    framework   = "ISO27001"
    code        = "A.5.10"
    title       = <<-SW360_TITLE_iso27001_a_5_10
Acceptable use of information and other associated assets
SW360_TITLE_iso27001_a_5_10
    description = <<-SW360_BODY_iso27001_a_5_10
Catalog control A.5.10. Map evidence collection, ownership, and automation to organizational policy. Framework: ISO/IEC 27001:2022.
SW360_BODY_iso27001_a_5_10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
