# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rs_an_07

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RS.AN-07"
  value = {
    framework   = "NIST"
    code        = "RS.AN-07"
    title       = <<-SW360_TITLE_nist_rs_an_07
Incident data and metadata are collected, and their integrity and provenance are preserved
SW360_TITLE_nist_rs_an_07
    description = <<-SW360_BODY_nist_rs_an_07
Catalog control RS.AN-07. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rs_an_07
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
