# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rc_rp_01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RC.RP-01"
  value = {
    framework   = "NIST"
    code        = "RC.RP-01"
    title       = <<-SW360_TITLE_nist_rc_rp_01
The recovery portion of the incident response plan is executed once initiated from the incident response process
SW360_TITLE_nist_rc_rp_01
    description = <<-SW360_BODY_nist_rc_rp_01
Catalog control RC.RP-01. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rc_rp_01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
