# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_sc_01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.SC-01"
  value = {
    framework   = "NIST"
    code        = "GV.SC-01"
    title       = <<-SW360_TITLE_nist_gv_sc_01
A cybersecurity supply chain risk management program, strategy, objectives, policies, and processes are established and agreed to by organizational stakeholders
SW360_TITLE_nist_gv_sc_01
    description = <<-SW360_BODY_nist_gv_sc_01
Catalog control GV.SC-01. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_sc_01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
