# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sc_17

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SC-17"
  value = {
    framework   = "FEDRAMP"
    code        = "SC-17"
    title       = <<-SW360_TITLE_fedramp_sc_17
Public Key Infrastructure Certificates
SW360_TITLE_fedramp_sc_17
    description = <<-SW360_BODY_fedramp_sc_17
Catalog control SC-17. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sc_17
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
