# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_sc_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.SC-05"
  value = {
    framework   = "NIST"
    code        = "GV.SC-05"
    title       = <<-SW360_TITLE_nist_gv_sc_05
Requirements to address cybersecurity risks in supply chains are established, prioritized, and integrated into contracts and other types of agreements with suppliers and other relevant third parties
SW360_TITLE_nist_gv_sc_05
    description = <<-SW360_BODY_nist_gv_sc_05
Catalog control GV.SC-05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_sc_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
