# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug ccpa_1798_150

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CCPA 1798.150"
  value = {
    framework   = "CCPA"
    code        = "1798.150"
    title       = <<-SW360_TITLE_ccpa_1798_150
CCPA 1798.150 — Reasonable security procedures and practices
SW360_TITLE_ccpa_1798_150
    description = <<-SW360_BODY_ccpa_1798_150
Catalog control 1798.150. Map evidence collection, ownership, and automation to organizational policy. Framework: California Consumer Privacy Act — selected Civil Code sections.
SW360_BODY_ccpa_1798_150
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
