# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sc_7_5

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SC-7.5"
  value = {
    framework   = "FEDRAMP"
    code        = "SC-7.5"
    title       = <<-SW360_TITLE_fedramp_sc_7_5
Deny by Default — Allow by Exception
SW360_TITLE_fedramp_sc_7_5
    description = <<-SW360_BODY_fedramp_sc_7_5
Catalog control SC-7.5. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sc_7_5
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
