# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_id_ra_04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST ID.RA-04"
  value = {
    framework   = "NIST"
    code        = "ID.RA-04"
    title       = <<-SW360_TITLE_nist_id_ra_04
Potential impacts and likelihoods of threats exploiting vulnerabilities are identified and recorded
SW360_TITLE_nist_id_ra_04
    description = <<-SW360_BODY_nist_id_ra_04
Catalog control ID.RA-04. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_id_ra_04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
