# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_16

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_16"
  value = {
    framework   = "GDPR"
    code        = "Art_16"
    title       = <<-SW360_TITLE_gdpr_art_16
GDPR Article 16 — Right to rectification
SW360_TITLE_gdpr_art_16
    description = <<-SW360_BODY_gdpr_art_16
Catalog control Art_16. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_16
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
