# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug iso27001_a_7_9

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "ISO27001 A.7.9"
  value = {
    framework   = "ISO27001"
    code        = "A.7.9"
    title       = <<-SW360_TITLE_iso27001_a_7_9
Security of assets off-premises
SW360_TITLE_iso27001_a_7_9
    description = <<-SW360_BODY_iso27001_a_7_9
Catalog control A.7.9. Map evidence collection, ownership, and automation to organizational policy. Framework: ISO/IEC 27001:2022.
SW360_BODY_iso27001_a_7_9
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
