# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_2_4

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 2.4"
  value = {
    framework   = "CIS"
    code        = "2.4"
    title       = <<-SW360_TITLE_cis_2_4
CIS Controls v8 Safeguard 2.4
SW360_TITLE_cis_2_4
    description = <<-SW360_BODY_cis_2_4
Catalog control 2.4. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_2_4
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
