# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rc_rp_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RC.RP-02"
  value = {
    framework   = "NIST"
    code        = "RC.RP-02"
    title       = <<-SW360_TITLE_nist_rc_rp_02
Recovery actions are selected, scoped, prioritized, and performed
SW360_TITLE_nist_rc_rp_02
    description = <<-SW360_BODY_nist_rc_rp_02
Catalog control RC.RP-02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rc_rp_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
