# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_at_01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.AT-01"
  value = {
    framework   = "NIST"
    code        = "PR.AT-01"
    title       = <<-SW360_TITLE_nist_pr_at_01
Personnel are provided with awareness and training so that they possess the knowledge and skills to perform general tasks with cybersecurity risks in mind
SW360_TITLE_nist_pr_at_01
    description = <<-SW360_BODY_nist_pr_at_01
Catalog control PR.AT-01. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_at_01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
