# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug pci_dss_8_6

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "PCI_DSS 8.6"
  value = {
    framework   = "PCI_DSS"
    code        = "8.6"
    title       = <<-SW360_TITLE_pci_dss_8_6
PCI DSS v4 — Requirement 8.6 (define testing procedures per PCI SSC standard)
SW360_TITLE_pci_dss_8_6
    description = <<-SW360_BODY_pci_dss_8_6
Catalog control 8.6. Map evidence collection, ownership, and automation to organizational policy. Framework: PCI DSS v4.
SW360_BODY_pci_dss_8_6
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
