# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ds_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.DS-02"
  value = {
    framework   = "NIST"
    code        = "PR.DS-02"
    title       = <<-SW360_TITLE_nist_pr_ds_02
The confidentiality, integrity, and availability of data-in-transit are protected
SW360_TITLE_nist_pr_ds_02
    description = <<-SW360_BODY_nist_pr_ds_02
Catalog control PR.DS-02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ds_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
