# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rc_co_03

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RC.CO-03"
  value = {
    framework   = "NIST"
    code        = "RC.CO-03"
    title       = <<-SW360_TITLE_nist_rc_co_03
Recovery activities and progress in restoring operational capabilities are communicated to designated internal and external stakeholders
SW360_TITLE_nist_rc_co_03
    description = <<-SW360_BODY_nist_rc_co_03
Catalog control RC.CO-03. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rc_co_03
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
