# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_33

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_33"
  value = {
    framework   = "GDPR"
    code        = "Art_33"
    title       = <<-SW360_TITLE_gdpr_art_33
GDPR Article 33 — Notification of a personal data breach to the supervisory authority
SW360_TITLE_gdpr_art_33
    description = <<-SW360_BODY_gdpr_art_33
Catalog control Art_33. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_33
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
