# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO05"
  value = {
    framework   = "COBIT"
    code        = "APO05"
    title       = <<-SW360_TITLE_cobit_apo05
COBIT 2019 — APO05 Managed portfolio
SW360_TITLE_cobit_apo05
    description = <<-SW360_BODY_cobit_apo05
Catalog control APO05. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
