# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rs_co_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RS.CO-02"
  value = {
    framework   = "NIST"
    code        = "RS.CO-02"
    title       = <<-SW360_TITLE_nist_rs_co_02
Internal and external stakeholders are notified of incidents
SW360_TITLE_nist_rs_co_02
    description = <<-SW360_BODY_nist_rs_co_02
Catalog control RS.CO-02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rs_co_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
