# SecureWatch360 Policy Pack — full catalog (995 controls)
# Generated by scripts/generate-policy-pack-iac.mjs from 20260425150000_policy_pack_full_catalog.sql
# Reference layout for GET /api/policy/export/terraform — copy into your infra repo.

variable "enforcement_mode" {
  description = "Global enforcement mode: advisory | enforced"
  type        = string
  default     = "advisory"
}

locals {
  policy_control_slugs = jsondecode(file("${path.module}/generated/control_slugs.json"))
}

module "policy_control" {
  for_each         = toset(local.policy_control_slugs)
  source           = "./modules/policies/${each.key}"
  enforcement_mode = var.enforcement_mode
}

output "all_controls" {
  description = "All provisioned policy controls (SecureWatch360 catalog)"
  value       = [for k, m in module.policy_control : m.securewatch360_control]
}

output "control_count" {
  value = length(local.policy_control_slugs)
}
