# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sc_21

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SC-21"
  value = {
    framework   = "FEDRAMP"
    code        = "SC-21"
    title       = <<-SW360_TITLE_fedramp_sc_21
Secure Name/Address Resolution Service (Recursive or Caching Resolver)
SW360_TITLE_fedramp_sc_21
    description = <<-SW360_BODY_fedramp_sc_21
Catalog control SC-21. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sc_21
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
