# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_edm04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT EDM04"
  value = {
    framework   = "COBIT"
    code        = "EDM04"
    title       = <<-SW360_TITLE_cobit_edm04
COBIT 2019 — EDM04 Resource optimization
SW360_TITLE_cobit_edm04
    description = <<-SW360_BODY_cobit_edm04
Catalog control EDM04. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_edm04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
