# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_edm03

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT EDM03"
  value = {
    framework   = "COBIT"
    code        = "EDM03"
    title       = <<-SW360_TITLE_cobit_edm03
COBIT 2019 — EDM03 Risk optimization
SW360_TITLE_cobit_edm03
    description = <<-SW360_BODY_cobit_edm03
Catalog control EDM03. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_edm03
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
