# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_6_6

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 6.6"
  value = {
    framework   = "CIS"
    code        = "6.6"
    title       = <<-SW360_TITLE_cis_6_6
CIS Controls v8 Safeguard 6.6
SW360_TITLE_cis_6_6
    description = <<-SW360_BODY_cis_6_6
Catalog control 6.6. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_6_6
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
