# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_si_7_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SI-7.1"
  value = {
    framework   = "FEDRAMP"
    code        = "SI-7.1"
    title       = <<-SW360_TITLE_fedramp_si_7_1
Integrity Checks
SW360_TITLE_fedramp_si_7_1
    description = <<-SW360_BODY_fedramp_si_7_1
Catalog control SI-7.1. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_si_7_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
