# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO10"
  value = {
    framework   = "COBIT"
    code        = "APO10"
    title       = <<-SW360_TITLE_cobit_apo10
COBIT 2019 — APO10 Managed vendors
SW360_TITLE_cobit_apo10
    description = <<-SW360_BODY_cobit_apo10
Catalog control APO10. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
