# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug soc2_cc3_3

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "SOC2 CC3.3"
  value = {
    framework   = "SOC2"
    code        = "CC3.3"
    title       = <<-SW360_TITLE_soc2_cc3_3
SOC 2 (TSC Security) — CC3.3 (Risk assessment)
SW360_TITLE_soc2_cc3_3
    description = <<-SW360_BODY_soc2_cc3_3
Catalog control CC3.3. Map evidence collection, ownership, and automation to organizational policy. Framework: SOC 2 (TSC Security).
SW360_BODY_soc2_cc3_3
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
