# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_de_ae_07

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST DE.AE-07"
  value = {
    framework   = "NIST"
    code        = "DE.AE-07"
    title       = <<-SW360_TITLE_nist_de_ae_07
Cyber threat intelligence and other contextual information are integrated into the analysis
SW360_TITLE_nist_de_ae_07
    description = <<-SW360_BODY_nist_de_ae_07
Catalog control DE.AE-07. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_de_ae_07
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
