import { describe, expect, it, vi } from "vitest";

import {
  INVESTOR_DEMO_SCENARIO,
  INVESTOR_DEMO_SEED_REPORT_PREFIX,
} from "../demoSeedData";
import {
  resetInvestorDemoScenario,
  runInvestorDemoScenario,
  seedInvestorDemoScenario,
  type RunInvestorDemoClock,
  type RunInvestorDemoLogger,
} from "../demoRepository";
import { makeMemorySupabase } from "./_memorySupabase";

// ---------------------------------------------------------------------------
// seedInvestorDemoScenario
// ---------------------------------------------------------------------------

describe("seedInvestorDemoScenario", () => {
  it("inserts every section of INVESTOR_DEMO_SCENARIO", async () => {
    const { client, store } = makeMemorySupabase();
    const result = await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
    expect(result.counts.scenario).toBe(1);
    expect(result.counts.client).toBe(1);
    expect(result.counts.assets).toBe(INVESTOR_DEMO_SCENARIO.assets.length);
    expect(result.counts.events).toBe(INVESTOR_DEMO_SCENARIO.timeline.length);
    expect(result.counts.reasoning).toBe(INVESTOR_DEMO_SCENARIO.reasoning.length);
    expect(result.counts.actions).toBe(INVESTOR_DEMO_SCENARIO.actions.length);
    expect(result.counts.report_templates).toBe(
      INVESTOR_DEMO_SCENARIO.report_templates.length,
    );
    expect(result.counts.metrics).toBe(INVESTOR_DEMO_SCENARIO.metrics.length);

    expect(store.rows.get("demo_scenarios")?.length).toBe(1);
    expect(store.rows.get("demo_clients")?.length).toBe(1);
    expect(store.rows.get("demo_assets")?.length).toBe(4);
    expect(store.rows.get("demo_events")?.length).toBe(15);
    expect(store.rows.get("demo_agent_reasoning")?.length).toBe(3);
    expect(store.rows.get("demo_actions")?.length).toBe(4);
    expect(store.rows.get("demo_reports")?.length).toBe(2);
    expect(store.rows.get("demo_metrics")?.length).toBe(7);
  });

  it("seeds every event with status='pending' and emitted_at=null", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    for (const event of store.rows.get("demo_events") ?? []) {
      expect(event.status).toBe("pending");
      expect(event.emitted_at).toBeNull();
    }
  });

  it("seeds every action with status='pending' and confirmed=false", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);
    for (const action of store.rows.get("demo_actions") ?? []) {
      expect(action.status).toBe("pending");
      expect(action.confirmed).toBe(false);
      expect(action.executed_at).toBeNull();
    }
  });

  it("is idempotent — running seed twice never duplicates rows", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);
    const beforeCounts = {
      scenarios: store.rows.get("demo_scenarios")?.length,
      clients: store.rows.get("demo_clients")?.length,
      assets: store.rows.get("demo_assets")?.length,
      events: store.rows.get("demo_events")?.length,
      reasoning: store.rows.get("demo_agent_reasoning")?.length,
      actions: store.rows.get("demo_actions")?.length,
      reports: store.rows.get("demo_reports")?.length,
      metrics: store.rows.get("demo_metrics")?.length,
    };
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);
    expect({
      scenarios: store.rows.get("demo_scenarios")?.length,
      clients: store.rows.get("demo_clients")?.length,
      assets: store.rows.get("demo_assets")?.length,
      events: store.rows.get("demo_events")?.length,
      reasoning: store.rows.get("demo_agent_reasoning")?.length,
      actions: store.rows.get("demo_actions")?.length,
      reports: store.rows.get("demo_reports")?.length,
      metrics: store.rows.get("demo_metrics")?.length,
    }).toEqual(beforeCounts);
  });

  it("preserves generated reports (non-template) when re-seeding", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    const genReports = store.rows.get("demo_reports")!;
    genReports.push({
      id: "gen-1",
      scenario_key: INVESTOR_DEMO_SCENARIO.scenario_key,
      report_type: "executive",
      title: "Acme Dental: ransomware precursor contained in 33s",
      summary: "generated by run",
      report_json: { is_seed_template: false },
      created_at: new Date().toISOString(),
    });

    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    const reportsAfter = store.rows.get("demo_reports") ?? [];
    expect(reportsAfter.find((r) => r.id === "gen-1")).toBeDefined();
    expect(
      reportsAfter.filter((r) =>
        String(r.title).startsWith(INVESTOR_DEMO_SEED_REPORT_PREFIX),
      ).length,
    ).toBe(2);
  });

  it("captures supabase errors into result.errors but does not throw", async () => {
    const { client, store } = makeMemorySupabase();
    store.errors.set("insert:demo_assets", "simulated failure");
    const result = await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);
    expect(result.ok).toBe(false);
    expect(result.errors.some((e) => e.includes("simulated failure"))).toBe(true);
    expect(result.counts.assets).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// runInvestorDemoScenario
// ---------------------------------------------------------------------------

interface FakeClock extends RunInvestorDemoClock {
  totalSlept: number;
  /** Current virtual time in ms. */
  virtualNow: number;
}

function makeFakeClock(): FakeClock {
  const c: FakeClock = {
    totalSlept: 0,
    virtualNow: 0,
    now() {
      return c.virtualNow;
    },
    async sleep(ms: number) {
      c.totalSlept += ms;
      c.virtualNow += ms;
    },
  };
  return c;
}

function makeCapturingLogger(): RunInvestorDemoLogger & {
  messages: Array<{ message: string; ctx?: Record<string, unknown> }>;
} {
  const messages: Array<{ message: string; ctx?: Record<string, unknown> }> = [];
  return {
    messages,
    info(message, ctx) {
      messages.push({ message, ...(ctx ? { ctx } : {}) });
    },
  };
}

describe("runInvestorDemoScenario", () => {
  it("flips scenario status ready→running→completed and emits every event", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    const logger = makeCapturingLogger();
    const clock = makeFakeClock();
    const result = await runInvestorDemoScenario({ logger, clock }, client);

    expect(result.ok).toBe(true);
    expect(result.emittedEventCount).toBe(15);
    expect(result.errors).toEqual([]);

    const scenario = store.rows
      .get("demo_scenarios")
      ?.find((r) => r.scenario_key === INVESTOR_DEMO_SCENARIO.scenario_key);
    expect(scenario?.status).toBe("completed");

    for (const event of store.rows.get("demo_events") ?? []) {
      expect(event.status).toBe("emitted");
      expect(event.emitted_at).not.toBeNull();
    }
    expect(result.finalMetrics.length).toBe(INVESTOR_DEMO_SCENARIO.metrics.length);
    expect(logger.messages.length).toBe(15);
  });

  it("respects speedMultiplier — 10x finishes in roughly 5.5 virtual seconds", async () => {
    const { client } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    const clock = makeFakeClock();
    await runInvestorDemoScenario(
      { logger: makeCapturingLogger(), clock, speedMultiplier: 10 },
      client,
    );
    expect(clock.totalSlept).toBeLessThanOrEqual(5500);
  });

  it("rejects non-positive speedMultipliers", async () => {
    const { client } = makeMemorySupabase();
    await expect(
      runInvestorDemoScenario({ speedMultiplier: 0 }, client),
    ).rejects.toThrow(/invalid speedMultiplier/);
  });
});

// ---------------------------------------------------------------------------
// resetInvestorDemoScenario — full round-trip
// ---------------------------------------------------------------------------

describe("resetInvestorDemoScenario", () => {
  it("fully restores the scenario after a complete run", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    const seededEventStatuses = (store.rows.get("demo_events") ?? []).map(
      (e) => ({ event_order: e.event_order, status: e.status, emitted_at: e.emitted_at }),
    );
    const seededActionStatuses = (store.rows.get("demo_actions") ?? []).map(
      (a) => ({
        action_type: a.action_type,
        status: a.status,
        confirmed: a.confirmed,
        executed_at: a.executed_at,
        result_summary: a.result_summary,
      }),
    );
    const seededAssetStatuses = (store.rows.get("demo_assets") ?? []).map(
      (a) => ({ asset_name: a.asset_name, status: a.status }),
    );

    await runInvestorDemoScenario(
      { logger: makeCapturingLogger(), clock: makeFakeClock() },
      client,
    );

    const assets = store.rows.get("demo_assets")!;
    const laptop = assets.find((a) => a.asset_name === "LAPTOP-123")!;
    laptop.status = "isolated";

    const actions = store.rows.get("demo_actions")!;
    const isolate = actions.find((a) => a.action_type === "isolate_endpoint")!;
    isolate.status = "executed";
    isolate.confirmed = true;
    isolate.executed_at = new Date().toISOString();
    isolate.result_summary = "isolated (simulated)";

    const reports = store.rows.get("demo_reports")!;
    reports.push({
      id: "gen-exec",
      scenario_key: INVESTOR_DEMO_SCENARIO.scenario_key,
      report_type: "executive",
      title: "Acme Dental: contained in 33s",
      summary: "generated by run",
      report_json: { is_seed_template: false },
      created_at: new Date().toISOString(),
    });

    const resetResult = await resetInvestorDemoScenario(
      INVESTOR_DEMO_SCENARIO.scenario_key,
      client,
    );
    expect(resetResult.ok).toBe(true);
    expect(resetResult.errors).toEqual([]);
    expect(Object.values(resetResult.reset).every((v) => v === true)).toBe(true);

    const scenario = store.rows
      .get("demo_scenarios")
      ?.find((r) => r.scenario_key === INVESTOR_DEMO_SCENARIO.scenario_key);
    expect(scenario?.status).toBe("ready");

    const eventStatusesAfter = (store.rows.get("demo_events") ?? []).map(
      (e) => ({ event_order: e.event_order, status: e.status, emitted_at: e.emitted_at }),
    );
    expect(eventStatusesAfter).toEqual(seededEventStatuses);

    const actionStatusesAfter = (store.rows.get("demo_actions") ?? []).map(
      (a) => ({
        action_type: a.action_type,
        status: a.status,
        confirmed: a.confirmed,
        executed_at: a.executed_at,
        result_summary: a.result_summary,
      }),
    );
    expect(actionStatusesAfter).toEqual(seededActionStatuses);

    const assetStatusesAfter = (store.rows.get("demo_assets") ?? []).map(
      (a) => ({ asset_name: a.asset_name, status: a.status }),
    );
    expect(assetStatusesAfter).toEqual(seededAssetStatuses);

    const reportsAfter = store.rows.get("demo_reports") ?? [];
    expect(reportsAfter.length).toBe(2);
    for (const r of reportsAfter) {
      expect(String(r.title).startsWith(INVESTOR_DEMO_SEED_REPORT_PREFIX)).toBe(true);
    }
    expect(reportsAfter.find((r) => r.id === "gen-exec")).toBeUndefined();
  });

  it("captures supabase errors per step and reports a clean failure", async () => {
    const { client, store } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);
    store.errors.set("update:demo_actions", "actions reset failed");

    const result = await resetInvestorDemoScenario(
      INVESTOR_DEMO_SCENARIO.scenario_key,
      client,
    );
    expect(result.ok).toBe(false);
    expect(result.reset.action_statuses).toBe(false);
    expect(result.reset.event_statuses).toBe(true);
    expect(result.errors[0]).toMatch(/actions reset failed/);
  });
});

// ---------------------------------------------------------------------------
// Logger output shape
// ---------------------------------------------------------------------------

describe("run logger output shape", () => {
  it("formats each line with offset + event_type + title", async () => {
    const { client } = makeMemorySupabase();
    await seedInvestorDemoScenario(INVESTOR_DEMO_SCENARIO, client);

    const logger = {
      info: vi.fn(),
    } satisfies RunInvestorDemoLogger;

    await runInvestorDemoScenario({ logger, clock: makeFakeClock() }, client);

    expect(logger.info).toHaveBeenCalledTimes(15);
    const firstCall = logger.info.mock.calls[0]!;
    expect(firstCall[0]).toMatch(/^\[demo:run\] \+0s — demo_started:/);
  });
});
