# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rs_an_08

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RS.AN-08"
  value = {
    framework   = "NIST"
    code        = "RS.AN-08"
    title       = <<-SW360_TITLE_nist_rs_an_08
An incident's magnitude is estimated and validated
SW360_TITLE_nist_rs_an_08
    description = <<-SW360_BODY_nist_rs_an_08
Catalog control RS.AN-08. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rs_an_08
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
