# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_rr_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.RR-02"
  value = {
    framework   = "NIST"
    code        = "GV.RR-02"
    title       = <<-SW360_TITLE_nist_gv_rr_02
Roles, responsibilities, and authorities related to cybersecurity risk management are established, communicated, understood, and enforced
SW360_TITLE_nist_gv_rr_02
    description = <<-SW360_BODY_nist_gv_rr_02
Catalog control GV.RR-02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_rr_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
