# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug hipaa_164_312_d

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "HIPAA 164.312(d)"
  value = {
    framework   = "HIPAA"
    code        = "164.312(d)"
    title       = <<-SW360_TITLE_hipaa_164_312_d
HIPAA Security Rule 164.312(d) — Person or entity authentication
SW360_TITLE_hipaa_164_312_d
    description = <<-SW360_BODY_hipaa_164_312_d
Catalog control 164.312(d). Map evidence collection, ownership, and automation to organizational policy. Framework: HIPAA Security Rule (45 CFR Part 164 Subpart C).
SW360_BODY_hipaa_164_312_d
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
