/**
 * Agent 6: Quantum Risk & Crypto Agility Module
 * Sample payloads for testing, seeding, and demonstration purposes.
 * All data is synthetic — no client-specific information.
 */

import type {
  CryptoInventoryItem,
  RawScanFinding,
  QuantumReadinessAgentInput,
} from "./types";

// ── Sample Raw Scan Findings ──────────────────────────────────────────────────

export const SAMPLE_RAW_FINDINGS: RawScanFinding[] = [
  {
    findingId: "finding-001",
    category: "tls-configuration",
    title: "Weak TLS cipher suite detected: RSA-2048 / AES-128-CBC-SHA",
    description: "The endpoint is negotiating a cipher suite using RSA key exchange which is quantum-vulnerable.",
    severity: "high",
    metadata: {
      hostname: "api.example-corp.internal",
      ip: "10.0.1.45",
      port: 443,
      protocol: "HTTPS",
      asset_type: "api_gateway",
      tls_version: "TLSv1.2",
      algorithm: "RSA-2048",
      key_length: 2048,
      cipher_suite: "TLS_RSA_WITH_AES_128_CBC_SHA",
      certificate_subject: "CN=api.example-corp.internal",
      certificate_issuer: "CN=Example Corp CA",
      certificate_expiration: "2025-12-31T00:00:00.000Z",
      scanner: "tls-scanner",
    },
  },
  {
    findingId: "finding-002",
    category: "certificate-audit",
    title: "TLS 1.0 still enabled on legacy endpoint",
    description: "The service supports TLS 1.0 which is deprecated by NIST SP 800-52 Rev. 2.",
    severity: "critical",
    metadata: {
      hostname: "legacy-portal.example-corp.com",
      ip: "203.0.113.10",
      port: 443,
      asset_type: "public_web_app",
      tls_version: "TLSv1.0",
      algorithm: "RSA-2048",
      key_length: 2048,
      scanner: "network-scanner",
    },
  },
  {
    findingId: "finding-003",
    category: "crypto-algorithm",
    title: "ECDSA P-256 certificate on public-facing load balancer",
    description: "Public web application TLS certificate uses ECDSA P-256 which is vulnerable to Shor's algorithm.",
    severity: "high",
    metadata: {
      hostname: "www.example-corp.com",
      ip: "198.51.100.1",
      port: 443,
      asset_type: "public_web_app",
      tls_version: "TLSv1.3",
      algorithm: "ECDSA-P256",
      key_length: 256,
      certificate_subject: "CN=www.example-corp.com",
      certificate_issuer: "CN=Let's Encrypt Authority",
      certificate_expiration: "2025-09-15T00:00:00.000Z",
      scanner: "tls-scanner",
    },
  },
  {
    findingId: "finding-004",
    category: "database-encryption",
    title: "Database at-rest encryption uses AES-128",
    description: "Production database encryption key uses AES-128 which provides only ~64-bit security against Grover's algorithm.",
    severity: "medium",
    metadata: {
      service_name: "PostgreSQL Primary",
      asset_type: "database",
      algorithm: "AES-128",
      key_length: 128,
      cloud: "aws",
      region: "us-east-1",
      service: "AWS KMS",
      scanner: "cloud-config-scanner",
    },
  },
  {
    findingId: "finding-005",
    category: "ssh-key-audit",
    title: "SSH host key uses RSA-1024 (below minimum)",
    description: "SSH server presents a 1024-bit RSA host key which is critically weak both classically and against quantum attack.",
    severity: "critical",
    metadata: {
      hostname: "jumphost-01.example-corp.internal",
      ip: "10.0.0.5",
      port: 22,
      asset_type: "jump_host",
      algorithm: "RSA-1024",
      key_length: 1024,
      key_type: "RSA",
      scanner: "ssh-scanner",
    },
  },
  {
    findingId: "finding-006",
    category: "crypto-algorithm",
    title: "VPN gateway uses Diffie-Hellman group 2 (1024-bit)",
    description: "IKEv1 VPN tunnel negotiates DH group 2 which is 1024-bit classical DH, vulnerable to quantum and classical attacks.",
    severity: "critical",
    metadata: {
      hostname: "vpn-gw.example-corp.com",
      ip: "198.51.100.5",
      port: 500,
      asset_type: "vpn_gateway",
      algorithm: "DH-2048",
      protocol: "IKEv1",
      service_name: "IPSec VPN",
      scanner: "network-scanner",
    },
  },
  {
    findingId: "finding-007",
    category: "jwt-signing",
    title: "API authentication JWT signed with RS256 (RSA-2048 / SHA-256)",
    description: "JWT tokens for API authentication are signed using RS256. RSA-2048 is quantum-vulnerable.",
    severity: "high",
    metadata: {
      service_name: "Auth Service",
      asset_type: "identity_provider",
      algorithm: "RSA-2048",
      key_length: 2048,
      service: "JWT Signing",
      scanner: "api-security-scanner",
    },
  },
  {
    findingId: "finding-008",
    category: "crypto-algorithm",
    title: "ML-KEM-768 (CRYSTALS-Kyber) detected on new microservice",
    description: "Microservice correctly uses ML-KEM-768, a NIST PQC standard (FIPS 203). No action required.",
    severity: "info",
    metadata: {
      hostname: "pqc-service.example-corp.internal",
      service_name: "Quantum-Ready Microservice",
      algorithm: "ML-KEM-768",
      scanner: "api-security-scanner",
    },
  },
];

// ── Sample Pre-Enriched Inventory Items ───────────────────────────────────────

export const SAMPLE_INVENTORY_ITEMS: CryptoInventoryItem[] = [
  {
    id: "inv-001",
    clientId: "{{CLIENT_ID}}",
    assetId: "finding-001",
    scanId: "{{SCAN_ID}}",
    assetHostname: "api.example-corp.internal",
    assetIp: "10.0.1.45",
    assetType: "api_gateway",
    serviceName: "Internal API Gateway",
    port: 443,
    protocol: "HTTPS",
    cryptoUsage: "tls",
    algorithm: "RSA-2048",
    keyLength: 2048,
    certificateSubject: "CN=api.example-corp.internal",
    certificateIssuer: "CN=Example Corp CA",
    certificateExpiration: "2025-12-31T00:00:00.000Z",
    tlsVersion: "TLSv1.2",
    isQuantumVulnerable: true,
    quantumRiskLevel: "high",
    vulnerabilityStatus: "quantum_vulnerable",
    discoverySource: "tls-scanner",
    evidence: {
      harvestNowDecryptLaterRisk: true,
      normalizedAlgorithm: "RSA-2048",
      attackVectors: ["shor", "harvest-now-decrypt-later"],
      recommendedReplacements: ["ML-KEM-768", "ML-DSA-65"],
    },
  },
  {
    id: "inv-002",
    clientId: "{{CLIENT_ID}}",
    assetId: "finding-002",
    assetType: "public_web_app",
    assetHostname: "legacy-portal.example-corp.com",
    assetIp: "203.0.113.10",
    port: 443,
    cryptoUsage: "tls",
    algorithm: "RSA-2048",
    tlsVersion: "TLSv1.0",
    isQuantumVulnerable: true,
    quantumRiskLevel: "critical",
    vulnerabilityStatus: "quantum_vulnerable",
    discoverySource: "network-scanner",
    evidence: {
      harvestNowDecryptLaterRisk: true,
      tlsDeprecated: true,
    },
  },
  {
    id: "inv-003",
    clientId: "{{CLIENT_ID}}",
    assetId: "finding-005",
    assetHostname: "jumphost-01.example-corp.internal",
    assetType: "jump_host",
    port: 22,
    cryptoUsage: "ssh",
    algorithm: "RSA-1024",
    keyLength: 1024,
    isQuantumVulnerable: true,
    quantumRiskLevel: "critical",
    vulnerabilityStatus: "quantum_vulnerable",
    discoverySource: "ssh-scanner",
    evidence: {
      harvestNowDecryptLaterRisk: false,
    },
  },
  {
    id: "inv-004",
    clientId: "{{CLIENT_ID}}",
    assetId: "finding-008",
    assetHostname: "pqc-service.example-corp.internal",
    serviceName: "Quantum-Ready Microservice",
    cryptoUsage: "tls",
    algorithm: "ML-KEM-768",
    isQuantumVulnerable: false,
    quantumRiskLevel: "low",
    vulnerabilityStatus: "quantum_resistant",
    discoverySource: "api-security-scanner",
    evidence: {
      nistPqcStandard: "FIPS 203",
    },
  },
];

// ── Sample Agent Input ────────────────────────────────────────────────────────

export const SAMPLE_AGENT_INPUT: QuantumReadinessAgentInput = {
  tenantId: "{{TENANT_ID}}",
  scanRunId: "{{SCAN_RUN_ID}}",
  rawFindings: SAMPLE_RAW_FINDINGS,
  options: {
    includeVendorAssessment: false,
    includeHarvestNowAnalysis: true,
    frameworks: ["NIST SP 800-131A", "SOC 2", "ISO 27001:2022", "CMMC 2.0"],
    crqcYearsEstimate: 10,
  },
};
