# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_oc_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.OC-02"
  value = {
    framework   = "NIST"
    code        = "GV.OC-02"
    title       = <<-SW360_TITLE_nist_gv_oc_02
Internal and external stakeholders are understood, and their needs and expectations regarding cybersecurity risk management are understood and considered
SW360_TITLE_nist_gv_oc_02
    description = <<-SW360_BODY_nist_gv_oc_02
Catalog control GV.OC-02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_oc_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
