# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ps_06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.PS-06"
  value = {
    framework   = "NIST"
    code        = "PR.PS-06"
    title       = <<-SW360_TITLE_nist_pr_ps_06
Secure software development practices are integrated, and their performance is monitored throughout the software development life cycle
SW360_TITLE_nist_pr_ps_06
    description = <<-SW360_BODY_nist_pr_ps_06
Catalog control PR.PS-06. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ps_06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
