# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_rm_04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.RM-04"
  value = {
    framework   = "NIST"
    code        = "GV.RM-04"
    title       = <<-SW360_TITLE_nist_gv_rm_04
Strategic direction that describes appropriate risk response options is established and communicated
SW360_TITLE_nist_gv_rm_04
    description = <<-SW360_BODY_nist_gv_rm_04
Catalog control GV.RM-04. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_rm_04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
