# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_17_3

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 17.3"
  value = {
    framework   = "CIS"
    code        = "17.3"
    title       = <<-SW360_TITLE_cis_17_3
CIS Controls v8 Safeguard 17.3
SW360_TITLE_cis_17_3
    description = <<-SW360_BODY_cis_17_3
Catalog control 17.3. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_17_3
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
