# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cmmc_03_15_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CMMC 03.15.02"
  value = {
    framework   = "CMMC"
    code        = "03.15.02"
    title       = <<-SW360_TITLE_cmmc_03_15_02
System Security Plan
SW360_TITLE_cmmc_03_15_02
    description = <<-SW360_BODY_cmmc_03_15_02
Catalog control 03.15.02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-171 Rev3 security requirements (CMMC L2 technical practice catalog).
SW360_BODY_cmmc_03_15_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
