# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_3_14

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 3.14"
  value = {
    framework   = "CIS"
    code        = "3.14"
    title       = <<-SW360_TITLE_cis_3_14
CIS Controls v8 Safeguard 3.14
SW360_TITLE_cis_3_14
    description = <<-SW360_BODY_cis_3_14
Catalog control 3.14. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_3_14
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
