# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_cm_8_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP CM-8.1"
  value = {
    framework   = "FEDRAMP"
    code        = "CM-8.1"
    title       = <<-SW360_TITLE_fedramp_cm_8_1
Updates During Installation and Removal
SW360_TITLE_fedramp_cm_8_1
    description = <<-SW360_BODY_fedramp_cm_8_1
Catalog control CM-8.1. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_cm_8_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
