# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_7_11

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 7.11"
  value = {
    framework   = "CIS"
    code        = "7.11"
    title       = <<-SW360_TITLE_cis_7_11
CIS Controls v8 Safeguard 7.11
SW360_TITLE_cis_7_11
    description = <<-SW360_BODY_cis_7_11
Catalog control 7.11. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_7_11
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
