# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_pe_14

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP PE-14"
  value = {
    framework   = "FEDRAMP"
    code        = "PE-14"
    title       = <<-SW360_TITLE_fedramp_pe_14
Environmental Controls
SW360_TITLE_fedramp_pe_14
    description = <<-SW360_BODY_fedramp_pe_14
Catalog control PE-14. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_pe_14
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
