# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_48

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_48"
  value = {
    framework   = "GDPR"
    code        = "Art_48"
    title       = <<-SW360_TITLE_gdpr_art_48
GDPR Article 48 — Transfers not authorized by Union law
SW360_TITLE_gdpr_art_48
    description = <<-SW360_BODY_gdpr_art_48
Catalog control Art_48. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_48
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
