# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rs_ma_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RS.MA-05"
  value = {
    framework   = "NIST"
    code        = "RS.MA-05"
    title       = <<-SW360_TITLE_nist_rs_ma_05
The criteria for initiating incident recovery are applied
SW360_TITLE_nist_rs_ma_05
    description = <<-SW360_BODY_nist_rs_ma_05
Catalog control RS.MA-05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rs_ma_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
