# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_mea01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT MEA01"
  value = {
    framework   = "COBIT"
    code        = "MEA01"
    title       = <<-SW360_TITLE_cobit_mea01
COBIT 2019 — MEA01 Managed performance and conformance monitoring
SW360_TITLE_cobit_mea01
    description = <<-SW360_BODY_cobit_mea01
Catalog control MEA01. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_mea01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
