# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rc_co_04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RC.CO-04"
  value = {
    framework   = "NIST"
    code        = "RC.CO-04"
    title       = <<-SW360_TITLE_nist_rc_co_04
Public updates on incident recovery are shared using approved methods and messaging
SW360_TITLE_nist_rc_co_04
    description = <<-SW360_BODY_nist_rc_co_04
Catalog control RC.CO-04. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rc_co_04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
