# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug hipaa_164_310_d_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "HIPAA 164.310(d)(1)"
  value = {
    framework   = "HIPAA"
    code        = "164.310(d)(1)"
    title       = <<-SW360_TITLE_hipaa_164_310_d_1
HIPAA Security Rule 164.310(d)(1) — Device and media controls — disposal
SW360_TITLE_hipaa_164_310_d_1
    description = <<-SW360_BODY_hipaa_164_310_d_1
Catalog control 164.310(d)(1). Map evidence collection, ownership, and automation to organizational policy. Framework: HIPAA Security Rule (45 CFR Part 164 Subpart C).
SW360_BODY_hipaa_164_310_d_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
