# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_ac_20

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP AC-20"
  value = {
    framework   = "FEDRAMP"
    code        = "AC-20"
    title       = <<-SW360_TITLE_fedramp_ac_20
Use of External Systems
SW360_TITLE_fedramp_ac_20
    description = <<-SW360_BODY_fedramp_ac_20
Catalog control AC-20. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_ac_20
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
