# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ps_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.PS-05"
  value = {
    framework   = "NIST"
    code        = "PR.PS-05"
    title       = <<-SW360_TITLE_nist_pr_ps_05
Installation and execution of unauthorized software are prevented
SW360_TITLE_nist_pr_ps_05
    description = <<-SW360_BODY_nist_pr_ps_05
Catalog control PR.PS-05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ps_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
