# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ds_10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.DS-10"
  value = {
    framework   = "NIST"
    code        = "PR.DS-10"
    title       = <<-SW360_TITLE_nist_pr_ds_10
The confidentiality, integrity, and availability of data-in-use are protected
SW360_TITLE_nist_pr_ds_10
    description = <<-SW360_BODY_nist_pr_ds_10
Catalog control PR.DS-10. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ds_10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
