# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_de_cm_01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST DE.CM-01"
  value = {
    framework   = "NIST"
    code        = "DE.CM-01"
    title       = <<-SW360_TITLE_nist_de_cm_01
Networks and network services are monitored to find potentially adverse events
SW360_TITLE_nist_de_cm_01
    description = <<-SW360_BODY_nist_de_cm_01
Catalog control DE.CM-01. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_de_cm_01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
