# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_17

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_17"
  value = {
    framework   = "GDPR"
    code        = "Art_17"
    title       = <<-SW360_TITLE_gdpr_art_17
GDPR Article 17 — Right to erasure ('right to be forgotten')
SW360_TITLE_gdpr_art_17
    description = <<-SW360_BODY_gdpr_art_17
Catalog control Art_17. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_17
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
