/**
 * POST /api/simulation/run-demo
 *
 * Generates a realistic synthetic simulation report and writes it to
 * `.simulation-results/` so the SimulationDashboard can display it
 * without needing a local simulator process.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "crypto";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

function resolveSimulationResultsDir(): string {
  const fromEnv = process.env.SIMULATION_RESULTS_DIR?.trim();
  if (fromEnv) return path.isAbsolute(fromEnv) ? fromEnv : path.join(process.cwd(), fromEnv);
  return path.join(process.cwd(), ".simulation-results");
}

function buildDemoReport(runId: string) {
  const now = new Date().toISOString();
  const timelineEvents = [
    {
      phase: "asset_discovery",
      t_offset_seconds: 0,
      narrative:
        "Agent 1 initiates passive DNS enumeration, certificate transparency log query, and OSINT surface scan. 14 live subdomains discovered including mail, api, and legacy admin interfaces.",
    },
    {
      phase: "vuln_surface",
      t_offset_seconds: 42,
      narrative:
        "Agent 2 correlates discovered subdomains against CVE catalog. Identifies 3 critical (CVE-2024-3094, CVE-2024-21626, CVE-2023-44487), 7 high, and 12 medium severity findings across the asset surface.",
    },
    {
      phase: "policy_eval",
      t_offset_seconds: 88,
      narrative:
        "Decision engine applies SOC 2 + NIST CSF policy bindings. Critical findings escalated automatically. 2 require human-in-the-loop approval due to REMEDIATION_HUMAN_IN_THE_LOOP=true configuration.",
    },
    {
      phase: "remediation_routing",
      t_offset_seconds: 134,
      narrative:
        "Remediation agent creates 8 action tickets: 3 auto-remediated (patch commands executed), 2 queued for approval, 3 accepted as risk exceptions pending executive sign-off.",
    },
    {
      phase: "compliance_mapping",
      t_offset_seconds: 178,
      narrative:
        "Compliance agent maps 22 findings to SOC 2 CC6.x, NIST CSF ID.AM-1/PR.AC-1, and PCI-DSS Req 6.3.3 control requirements. Evidence records written to audit trail.",
    },
    {
      phase: "incident_lifecycle",
      t_offset_seconds: 219,
      narrative:
        "3 incidents transitioned through open → contained → remediated. Incident state machine validates each transition. Audit log entries written with actor, timestamp, and evidence links.",
    },
    {
      phase: "validation",
      t_offset_seconds: 265,
      narrative:
        "All 6 autonomy checklist validators acknowledged. Audit trail complete. Evidence export ready. Dashboard summary persisted for executive briefing.",
    },
  ];

  const summary = {
    runId,
    scenarioName: "Full SOC Autonomy — External Surface Scan + Compliance Closure",
    status: "passed",
    autonomyScore: 94,
    autonomyReadinessLabel: "Production-ready",
    agentsPassed: 6,
    agentsFailed: 0,
    controlsValidated:
      "SOC 2 CC6.1–CC6.8, NIST CSF ID.AM-1, PR.AC-1, DE.CM-8, PCI-DSS Req 6.3.3, HIPAA §164.312(a)(1). 22 control-to-finding mappings written. Evidence export chain intact.",
    remediationStatus:
      "3 of 8 actions auto-remediated; 2 pending approval; 3 risk-accepted. Mean time-to-contain: 134 s. All SLA timers within configured 72-hour window.",
    executiveSummary:
      "SecureWatch360 autonomously discovered, triaged, and began remediating a 22-finding external surface within 4.5 minutes. Critical findings were escalated and approval gates enforced per policy. Compliance mappings across SOC 2, NIST CSF, and PCI-DSS were written automatically with full audit trail. Zero analyst intervention required for standard-severity findings.",
    technicalSummary: `run_id: ${runId}\nscenario: external_surface_full_lifecycle\nagents_fired: [agent1_discovery, agent2_osint, decision_engine, remediation_agent, compliance_agent, incident_state_machine]\ncvss_max: 10.0 (CVE-2024-3094)\nfindings_total: 22 (crit=3, high=7, med=12)\nremediation_actions: 8 (auto=3, pending_approval=2, risk_accepted=3)\naudit_entries_written: 47\nevidence_records: 22\ncompli_frameworks: SOC2, NIST_CSF, PCI_DSS, HIPAA\ninngest_events_emitted: 14`,
    nextRecommendedAction:
      "Review the 2 pending approval requests and 3 risk exceptions in the Approval Requests view. Consider enabling auto-remediation for patch-class findings to reduce mean-time-to-remediate.",
    timelineEvents,
    simulation_demo_mode: true,
    demo_disclaimer:
      "This summary was generated by the SecureWatch360 demo simulation engine. Data is synthetic but structurally representative of a live tenant run.",
    demo_client_display_name: "SecureWatch360 Demo Tenant",
    generated_at: now,
  };

  return {
    run_id: runId,
    scenario: "external_surface_full_lifecycle",
    status: "passed",
    generated_at: now,
    dashboard_summary: summary,
  };
}

export async function POST() {
  try {
    const dir = resolveSimulationResultsDir();
    await fs.mkdir(dir, { recursive: true });

    const runId = randomUUID();
    const report = buildDemoReport(runId);
    const filePath = path.join(dir, `${runId}-simulation-report.json`);
    await fs.writeFile(filePath, JSON.stringify(report, null, 2), "utf8");

    return NextResponse.json({ ok: true, runId, summary: report.dashboard_summary });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}
