# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug iso27001_a_7_5

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "ISO27001 A.7.5"
  value = {
    framework   = "ISO27001"
    code        = "A.7.5"
    title       = <<-SW360_TITLE_iso27001_a_7_5
Protecting against physical and environmental threats
SW360_TITLE_iso27001_a_7_5
    description = <<-SW360_BODY_iso27001_a_7_5
Catalog control A.7.5. Map evidence collection, ownership, and automation to organizational policy. Framework: ISO/IEC 27001:2022.
SW360_BODY_iso27001_a_7_5
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
