# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_sc_06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.SC-06"
  value = {
    framework   = "NIST"
    code        = "GV.SC-06"
    title       = <<-SW360_TITLE_nist_gv_sc_06
Planning and due diligence are performed to reduce risks before entering into formal supplier or other third-party relationships
SW360_TITLE_nist_gv_sc_06
    description = <<-SW360_BODY_nist_gv_sc_06
Catalog control GV.SC-06. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_sc_06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
