# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_18_10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 18.10"
  value = {
    framework   = "CIS"
    code        = "18.10"
    title       = <<-SW360_TITLE_cis_18_10
CIS Controls v8 Safeguard 18.10
SW360_TITLE_cis_18_10
    description = <<-SW360_BODY_cis_18_10
Catalog control 18.10. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_18_10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
