# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_de_ae_04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST DE.AE-04"
  value = {
    framework   = "NIST"
    code        = "DE.AE-04"
    title       = <<-SW360_TITLE_nist_de_ae_04
The estimated impact and scope of adverse events are understood
SW360_TITLE_nist_de_ae_04
    description = <<-SW360_BODY_nist_de_ae_04
Catalog control DE.AE-04. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_de_ae_04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
