# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_32

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_32"
  value = {
    framework   = "GDPR"
    code        = "Art_32"
    title       = <<-SW360_TITLE_gdpr_art_32
GDPR Article 32 — Security of processing
SW360_TITLE_gdpr_art_32
    description = <<-SW360_BODY_gdpr_art_32
Catalog control Art_32. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_32
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
