# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_13_7

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 13.7"
  value = {
    framework   = "CIS"
    code        = "13.7"
    title       = <<-SW360_TITLE_cis_13_7
CIS Controls v8 Safeguard 13.7
SW360_TITLE_cis_13_7
    description = <<-SW360_BODY_cis_13_7
Catalog control 13.7. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_13_7
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
