# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_ir_6_3

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP IR-6.3"
  value = {
    framework   = "FEDRAMP"
    code        = "IR-6.3"
    title       = <<-SW360_TITLE_fedramp_ir_6_3
Supply Chain Coordination
SW360_TITLE_fedramp_ir_6_3
    description = <<-SW360_BODY_fedramp_ir_6_3
Catalog control IR-6.3. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_ir_6_3
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
