# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_dss02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT DSS02"
  value = {
    framework   = "COBIT"
    code        = "DSS02"
    title       = <<-SW360_TITLE_cobit_dss02
COBIT 2019 — DSS02 Managed service requests and incidents
SW360_TITLE_cobit_dss02
    description = <<-SW360_BODY_cobit_dss02
Catalog control DSS02. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_dss02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
