# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_oc_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.OC-05"
  value = {
    framework   = "NIST"
    code        = "GV.OC-05"
    title       = <<-SW360_TITLE_nist_gv_oc_05
Outcomes, capabilities, and services that the organization depends on are understood and communicated
SW360_TITLE_nist_gv_oc_05
    description = <<-SW360_BODY_nist_gv_oc_05
Catalog control GV.OC-05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_oc_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
