# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sa_11

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SA-11"
  value = {
    framework   = "FEDRAMP"
    code        = "SA-11"
    title       = <<-SW360_TITLE_fedramp_sa_11
Developer Testing and Evaluation
SW360_TITLE_fedramp_sa_11
    description = <<-SW360_BODY_fedramp_sa_11
Catalog control SA-11. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sa_11
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
