# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cmmc_03_14_03

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CMMC 03.14.03"
  value = {
    framework   = "CMMC"
    code        = "03.14.03"
    title       = <<-SW360_TITLE_cmmc_03_14_03
Security Alerts, Advisories, and Directives
SW360_TITLE_cmmc_03_14_03
    description = <<-SW360_BODY_cmmc_03_14_03
Catalog control 03.14.03. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-171 Rev3 security requirements (CMMC L2 technical practice catalog).
SW360_BODY_cmmc_03_14_03
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
