# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug hipaa_164_316_a

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "HIPAA 164.316(a)"
  value = {
    framework   = "HIPAA"
    code        = "164.316(a)"
    title       = <<-SW360_TITLE_hipaa_164_316_a
HIPAA Security Rule 164.316(a) — Policies and procedures
SW360_TITLE_hipaa_164_316_a
    description = <<-SW360_BODY_hipaa_164_316_a
Catalog control 164.316(a). Map evidence collection, ownership, and automation to organizational policy. Framework: HIPAA Security Rule (45 CFR Part 164 Subpart C).
SW360_BODY_hipaa_164_316_a
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
