# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_bai11

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT BAI11"
  value = {
    framework   = "COBIT"
    code        = "BAI11"
    title       = <<-SW360_TITLE_cobit_bai11
COBIT 2019 — BAI11 Managed projects
SW360_TITLE_cobit_bai11
    description = <<-SW360_BODY_cobit_bai11
Catalog control BAI11. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_bai11
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
