# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_1_3

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 1.3"
  value = {
    framework   = "CIS"
    code        = "1.3"
    title       = <<-SW360_TITLE_cis_1_3
CIS Controls v8 Safeguard 1.3
SW360_TITLE_cis_1_3
    description = <<-SW360_BODY_cis_1_3
Catalog control 1.3. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_1_3
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
