# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_9_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 9.1"
  value = {
    framework   = "CIS"
    code        = "9.1"
    title       = <<-SW360_TITLE_cis_9_1
CIS Controls v8 Safeguard 9.1
SW360_TITLE_cis_9_1
    description = <<-SW360_BODY_cis_9_1
Catalog control 9.1. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_9_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
