# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_mp_6

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP MP-6"
  value = {
    framework   = "FEDRAMP"
    code        = "MP-6"
    title       = <<-SW360_TITLE_fedramp_mp_6
Media Sanitization
SW360_TITLE_fedramp_mp_6
    description = <<-SW360_BODY_fedramp_mp_6
Catalog control MP-6. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_mp_6
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
