# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug ccpa_1798_130

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CCPA 1798.130"
  value = {
    framework   = "CCPA"
    code        = "1798.130"
    title       = <<-SW360_TITLE_ccpa_1798_130
CCPA 1798.130 — Notice at collection
SW360_TITLE_ccpa_1798_130
    description = <<-SW360_BODY_ccpa_1798_130
Catalog control 1798.130. Map evidence collection, ownership, and automation to organizational policy. Framework: California Consumer Privacy Act — selected Civil Code sections.
SW360_BODY_ccpa_1798_130
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
