# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug pci_dss_2_2

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "PCI_DSS 2.2"
  value = {
    framework   = "PCI_DSS"
    code        = "2.2"
    title       = <<-SW360_TITLE_pci_dss_2_2
PCI DSS v4 — Requirement 2.2 (define testing procedures per PCI SSC standard)
SW360_TITLE_pci_dss_2_2
    description = <<-SW360_BODY_pci_dss_2_2
Catalog control 2.2. Map evidence collection, ownership, and automation to organizational policy. Framework: PCI DSS v4.
SW360_BODY_pci_dss_2_2
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
