# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo11

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO11"
  value = {
    framework   = "COBIT"
    code        = "APO11"
    title       = <<-SW360_TITLE_cobit_apo11
COBIT 2019 — APO11 Managed quality
SW360_TITLE_cobit_apo11
    description = <<-SW360_BODY_cobit_apo11
Catalog control APO11. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo11
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
