# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo14

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO14"
  value = {
    framework   = "COBIT"
    code        = "APO14"
    title       = <<-SW360_TITLE_cobit_apo14
COBIT 2019 — APO14 Managed data
SW360_TITLE_cobit_apo14
    description = <<-SW360_BODY_cobit_apo14
Catalog control APO14. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo14
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
