# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_18

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_18"
  value = {
    framework   = "GDPR"
    code        = "Art_18"
    title       = <<-SW360_TITLE_gdpr_art_18
GDPR Article 18 — Right to restriction of processing
SW360_TITLE_gdpr_art_18
    description = <<-SW360_BODY_gdpr_art_18
Catalog control Art_18. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_18
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
