# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO01"
  value = {
    framework   = "COBIT"
    code        = "APO01"
    title       = <<-SW360_TITLE_cobit_apo01
COBIT 2019 — APO01 Managed I&T management framework
SW360_TITLE_cobit_apo01
    description = <<-SW360_BODY_cobit_apo01
Catalog control APO01. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
