# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sa_22

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SA-22"
  value = {
    framework   = "FEDRAMP"
    code        = "SA-22"
    title       = <<-SW360_TITLE_fedramp_sa_22
Unsupported System Components
SW360_TITLE_fedramp_sa_22
    description = <<-SW360_BODY_fedramp_sa_22
Catalog control SA-22. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sa_22
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
