# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_ma_4

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP MA-4"
  value = {
    framework   = "FEDRAMP"
    code        = "MA-4"
    title       = <<-SW360_TITLE_fedramp_ma_4
Nonlocal Maintenance
SW360_TITLE_fedramp_ma_4
    description = <<-SW360_BODY_fedramp_ma_4
Catalog control MA-4. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_ma_4
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
