# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_dss05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT DSS05"
  value = {
    framework   = "COBIT"
    code        = "DSS05"
    title       = <<-SW360_TITLE_cobit_dss05
COBIT 2019 — DSS05 Managed security services
SW360_TITLE_cobit_dss05
    description = <<-SW360_BODY_cobit_dss05
Catalog control DSS05. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_dss05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
