# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_12_2

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 12.2"
  value = {
    framework   = "CIS"
    code        = "12.2"
    title       = <<-SW360_TITLE_cis_12_2
CIS Controls v8 Safeguard 12.2
SW360_TITLE_cis_12_2
    description = <<-SW360_BODY_cis_12_2
Catalog control 12.2. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_12_2
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
