# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_id_im_02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST ID.IM-02"
  value = {
    framework   = "NIST"
    code        = "ID.IM-02"
    title       = <<-SW360_TITLE_nist_id_im_02
Improvements are identified from security tests and exercises, including those done in coordination with suppliers and relevant third parties
SW360_TITLE_nist_id_im_02
    description = <<-SW360_BODY_nist_id_im_02
Catalog control ID.IM-02. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_id_im_02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
