# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_ra_2

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP RA-2"
  value = {
    framework   = "FEDRAMP"
    code        = "RA-2"
    title       = <<-SW360_TITLE_fedramp_ra_2
Security Categorization
SW360_TITLE_fedramp_ra_2
    description = <<-SW360_BODY_fedramp_ra_2
Catalog control RA-2. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_ra_2
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
