# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_rr_03

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.RR-03"
  value = {
    framework   = "NIST"
    code        = "GV.RR-03"
    title       = <<-SW360_TITLE_nist_gv_rr_03
Adequate resources are allocated commensurate with the cybersecurity risk strategy, roles, responsibilities, and policies
SW360_TITLE_nist_gv_rr_03
    description = <<-SW360_BODY_nist_gv_rr_03
Catalog control GV.RR-03. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_rr_03
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
