# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_mea04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT MEA04"
  value = {
    framework   = "COBIT"
    code        = "MEA04"
    title       = <<-SW360_TITLE_cobit_mea04
COBIT 2019 — MEA04 Managed assurance
SW360_TITLE_cobit_mea04
    description = <<-SW360_BODY_cobit_mea04
Catalog control MEA04. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_mea04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
