# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_id_im_01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST ID.IM-01"
  value = {
    framework   = "NIST"
    code        = "ID.IM-01"
    title       = <<-SW360_TITLE_nist_id_im_01
Improvements are identified from evaluations
SW360_TITLE_nist_id_im_01
    description = <<-SW360_BODY_nist_id_im_01
Catalog control ID.IM-01. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_id_im_01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
