# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug hipaa_164_316_b_2_i

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "HIPAA 164.316(b)(2)(i)"
  value = {
    framework   = "HIPAA"
    code        = "164.316(b)(2)(i)"
    title       = <<-SW360_TITLE_hipaa_164_316_b_2_i
HIPAA Security Rule 164.316(b)(2)(i) — Availability
SW360_TITLE_hipaa_164_316_b_2_i
    description = <<-SW360_BODY_hipaa_164_316_b_2_i
Catalog control 164.316(b)(2)(i). Map evidence collection, ownership, and automation to organizational policy. Framework: HIPAA Security Rule (45 CFR Part 164 Subpart C).
SW360_BODY_hipaa_164_316_b_2_i
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
