# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_pe_3

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP PE-3"
  value = {
    framework   = "FEDRAMP"
    code        = "PE-3"
    title       = <<-SW360_TITLE_fedramp_pe_3
Physical Access Control
SW360_TITLE_fedramp_pe_3
    description = <<-SW360_BODY_fedramp_pe_3
Catalog control PE-3. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_pe_3
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
