# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_sc_09

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.SC-09"
  value = {
    framework   = "NIST"
    code        = "GV.SC-09"
    title       = <<-SW360_TITLE_nist_gv_sc_09
Supply chain security practices are integrated into cybersecurity and enterprise risk management programs, and their performance is monitored throughout the technology product and service life cycle
SW360_TITLE_nist_gv_sc_09
    description = <<-SW360_BODY_nist_gv_sc_09
Catalog control GV.SC-09. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_sc_09
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
