# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_sc_08

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.SC-08"
  value = {
    framework   = "NIST"
    code        = "GV.SC-08"
    title       = <<-SW360_TITLE_nist_gv_sc_08
Relevant suppliers and other third parties are included in incident planning, response, and recovery activities
SW360_TITLE_nist_gv_sc_08
    description = <<-SW360_BODY_nist_gv_sc_08
Catalog control GV.SC-08. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_sc_08
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
