# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo12

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO12"
  value = {
    framework   = "COBIT"
    code        = "APO12"
    title       = <<-SW360_TITLE_cobit_apo12
COBIT 2019 — APO12 Managed risk
SW360_TITLE_cobit_apo12
    description = <<-SW360_BODY_cobit_apo12
Catalog control APO12. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo12
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
