# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug soc2_cc1_2

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "SOC2 CC1.2"
  value = {
    framework   = "SOC2"
    code        = "CC1.2"
    title       = <<-SW360_TITLE_soc2_cc1_2
SOC 2 (TSC Security) — CC1.2 (Control environment)
SW360_TITLE_soc2_cc1_2
    description = <<-SW360_BODY_soc2_cc1_2
Catalog control CC1.2. Map evidence collection, ownership, and automation to organizational policy. Framework: SOC 2 (TSC Security).
SW360_BODY_soc2_cc1_2
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
