# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_oc_01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.OC-01"
  value = {
    framework   = "NIST"
    code        = "GV.OC-01"
    title       = <<-SW360_TITLE_nist_gv_oc_01
The organizational mission is understood and informs cybersecurity risk management
SW360_TITLE_nist_gv_oc_01
    description = <<-SW360_BODY_nist_gv_oc_01
Catalog control GV.OC-01. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_oc_01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
