# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug pci_dss_11_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "PCI_DSS 11.1"
  value = {
    framework   = "PCI_DSS"
    code        = "11.1"
    title       = <<-SW360_TITLE_pci_dss_11_1
PCI DSS v4 — Requirement 11.1 (define testing procedures per PCI SSC standard)
SW360_TITLE_pci_dss_11_1
    description = <<-SW360_BODY_pci_dss_11_1
Catalog control 11.1. Map evidence collection, ownership, and automation to organizational policy. Framework: PCI DSS v4.
SW360_BODY_pci_dss_11_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
