# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ir_03

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.IR-03"
  value = {
    framework   = "NIST"
    code        = "PR.IR-03"
    title       = <<-SW360_TITLE_nist_pr_ir_03
Mechanisms are implemented to achieve resilience requirements in normal and adverse situations
SW360_TITLE_nist_pr_ir_03
    description = <<-SW360_BODY_nist_pr_ir_03
Catalog control PR.IR-03. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ir_03
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
