# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rc_rp_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RC.RP-05"
  value = {
    framework   = "NIST"
    code        = "RC.RP-05"
    title       = <<-SW360_TITLE_nist_rc_rp_05
The integrity of restored assets is verified, systems and services are restored, and normal operating status is confirmed
SW360_TITLE_nist_rc_rp_05
    description = <<-SW360_BODY_nist_rc_rp_05
Catalog control RC.RP-05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rc_rp_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
