# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_id_ra_09

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST ID.RA-09"
  value = {
    framework   = "NIST"
    code        = "ID.RA-09"
    title       = <<-SW360_TITLE_nist_id_ra_09
The authenticity and integrity of hardware and software are assessed prior to acquisition and use
SW360_TITLE_nist_id_ra_09
    description = <<-SW360_BODY_nist_id_ra_09
Catalog control ID.RA-09. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_id_ra_09
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
