# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_6

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_6"
  value = {
    framework   = "GDPR"
    code        = "Art_6"
    title       = <<-SW360_TITLE_gdpr_art_6
GDPR Article 6 — Lawfulness of processing
SW360_TITLE_gdpr_art_6
    description = <<-SW360_BODY_gdpr_art_6
Catalog control Art_6. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_6
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
