# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_mea02

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT MEA02"
  value = {
    framework   = "COBIT"
    code        = "MEA02"
    title       = <<-SW360_TITLE_cobit_mea02
COBIT 2019 — MEA02 Managed system of internal control
SW360_TITLE_cobit_mea02
    description = <<-SW360_BODY_cobit_mea02
Catalog control MEA02. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_mea02
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
