# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_dss06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT DSS06"
  value = {
    framework   = "COBIT"
    code        = "DSS06"
    title       = <<-SW360_TITLE_cobit_dss06
COBIT 2019 — DSS06 Managed business process controls
SW360_TITLE_cobit_dss06
    description = <<-SW360_BODY_cobit_dss06
Catalog control DSS06. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_dss06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
