# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ds_11

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.DS-11"
  value = {
    framework   = "NIST"
    code        = "PR.DS-11"
    title       = <<-SW360_TITLE_nist_pr_ds_11
Backups of data are created, protected, maintained, and tested
SW360_TITLE_nist_pr_ds_11
    description = <<-SW360_BODY_nist_pr_ds_11
Catalog control PR.DS-11. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ds_11
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
