# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sr_12

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SR-12"
  value = {
    framework   = "FEDRAMP"
    code        = "SR-12"
    title       = <<-SW360_TITLE_fedramp_sr_12
Component Disposal
SW360_TITLE_fedramp_sr_12
    description = <<-SW360_BODY_fedramp_sr_12
Catalog control SR-12. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sr_12
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
