# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_apo06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT APO06"
  value = {
    framework   = "COBIT"
    code        = "APO06"
    title       = <<-SW360_TITLE_cobit_apo06
COBIT 2019 — APO06 Managed budget and costs
SW360_TITLE_cobit_apo06
    description = <<-SW360_BODY_cobit_apo06
Catalog control APO06. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_apo06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
