# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rc_rp_06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RC.RP-06"
  value = {
    framework   = "NIST"
    code        = "RC.RP-06"
    title       = <<-SW360_TITLE_nist_rc_rp_06
The end of incident recovery is declared based on criteria, and incident-related documentation is completed
SW360_TITLE_nist_rc_rp_06
    description = <<-SW360_BODY_nist_rc_rp_06
Catalog control RC.RP-06. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rc_rp_06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
