# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_35

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_35"
  value = {
    framework   = "GDPR"
    code        = "Art_35"
    title       = <<-SW360_TITLE_gdpr_art_35
GDPR Article 35 — Data protection impact assessment
SW360_TITLE_gdpr_art_35
    description = <<-SW360_BODY_gdpr_art_35
Catalog control Art_35. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_35
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
