/**
 * Reads root .env.local and writes the VITE_-prefixed equivalents to
 * ui/.env.local so the Vite build always has the same credentials as Next.js.
 * Single source of truth: root .env.local.
 *
 * Mappings applied:
 *   NEXT_PUBLIC_SUPABASE_URL  → VITE_SUPABASE_URL
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY → VITE_SUPABASE_ANON_KEY
 *
 * Any VITE_* vars already in root .env.local are forwarded as-is.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const rootEnvFile = join(root, ".env.local");
const uiEnvFile = join(root, "ui", ".env.local");

if (!existsSync(rootEnvFile)) {
  console.warn("[prep-ui-env] No root .env.local found — ui/.env.local not updated.");
  process.exit(0);
}

/** Parse a .env file into a key→value map (ignores comments and blank lines). */
function parseEnv(filePath) {
  const lines = readFileSync(filePath, "utf8").split("\n");
  const map = new Map();
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 1) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    map.set(key, value);
  }
  return map;
}

const rootVars = parseEnv(rootEnvFile);

const MAPPINGS = [
  ["NEXT_PUBLIC_SUPABASE_URL", "VITE_SUPABASE_URL"],
  ["NEXT_PUBLIC_SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"],
];

const out = new Map();

// Apply NEXT_PUBLIC_ → VITE_ mappings
for (const [src, dest] of MAPPINGS) {
  const val = rootVars.get(src);
  if (val) {
    out.set(dest, val);
  }
}

// Forward any VITE_* vars already in root .env.local (they take precedence)
for (const [key, val] of rootVars) {
  if (key.startsWith("VITE_")) {
    out.set(key, val);
  }
}

// Always disable the local demo-user fallback in real builds
out.set("VITE_DEMO_MODE", "0");

const content =
  "# Auto-generated by scripts/prep-ui-env.mjs — DO NOT EDIT MANUALLY.\n" +
  "# Edit root .env.local instead; this file is regenerated on every ui:build.\n" +
  [...out.entries()].map(([k, v]) => `${k}=${v}`).join("\n") +
  "\n";

writeFileSync(uiEnvFile, content, "utf8");
console.log(`[prep-ui-env] Wrote ${out.size} vars to ui/.env.local`);
