# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_13

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_13"
  value = {
    framework   = "GDPR"
    code        = "Art_13"
    title       = <<-SW360_TITLE_gdpr_art_13
GDPR Article 13 — Information to be provided when collected from the data subject
SW360_TITLE_gdpr_art_13
    description = <<-SW360_BODY_gdpr_art_13
Catalog control Art_13. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_13
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
