# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_dss01

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT DSS01"
  value = {
    framework   = "COBIT"
    code        = "DSS01"
    title       = <<-SW360_TITLE_cobit_dss01
COBIT 2019 — DSS01 Managed operations
SW360_TITLE_cobit_dss01
    description = <<-SW360_BODY_cobit_dss01
Catalog control DSS01. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_dss01
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
