# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_edm05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT EDM05"
  value = {
    framework   = "COBIT"
    code        = "EDM05"
    title       = <<-SW360_TITLE_cobit_edm05
COBIT 2019 — EDM05 Stakeholder engagement
SW360_TITLE_cobit_edm05
    description = <<-SW360_BODY_cobit_edm05
Catalog control EDM05. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_edm05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
