# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_de_cm_09

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST DE.CM-09"
  value = {
    framework   = "NIST"
    code        = "DE.CM-09"
    title       = <<-SW360_TITLE_nist_de_cm_09
Computing hardware and software, runtime environments, and their data are monitored to find potentially adverse events
SW360_TITLE_nist_de_cm_09
    description = <<-SW360_BODY_nist_de_cm_09
Catalog control DE.CM-09. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_de_cm_09
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
