# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_bai08

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT BAI08"
  value = {
    framework   = "COBIT"
    code        = "BAI08"
    title       = <<-SW360_TITLE_cobit_bai08
COBIT 2019 — BAI08 Managed knowledge
SW360_TITLE_cobit_bai08
    description = <<-SW360_BODY_cobit_bai08
Catalog control BAI08. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_bai08
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
