# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_id_ra_10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST ID.RA-10"
  value = {
    framework   = "NIST"
    code        = "ID.RA-10"
    title       = <<-SW360_TITLE_nist_id_ra_10
Critical suppliers are assessed prior to acquisition
SW360_TITLE_nist_id_ra_10
    description = <<-SW360_BODY_nist_id_ra_10
Catalog control ID.RA-10. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_id_ra_10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
