# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_aa_06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.AA-06"
  value = {
    framework   = "NIST"
    code        = "PR.AA-06"
    title       = <<-SW360_TITLE_nist_pr_aa_06
Physical access to assets is managed, monitored, and enforced commensurate with risk
SW360_TITLE_nist_pr_aa_06
    description = <<-SW360_BODY_nist_pr_aa_06
Catalog control PR.AA-06. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_aa_06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
