# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_dss04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT DSS04"
  value = {
    framework   = "COBIT"
    code        = "DSS04"
    title       = <<-SW360_TITLE_cobit_dss04
COBIT 2019 — DSS04 Managed continuity
SW360_TITLE_cobit_dss04
    description = <<-SW360_BODY_cobit_dss04
Catalog control DSS04. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_dss04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
