# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug soc2_cc9_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "SOC2 CC9.1"
  value = {
    framework   = "SOC2"
    code        = "CC9.1"
    title       = <<-SW360_TITLE_soc2_cc9_1
SOC 2 (TSC Security) — CC9.1 (Risk mitigation)
SW360_TITLE_soc2_cc9_1
    description = <<-SW360_BODY_soc2_cc9_1
Catalog control CC9.1. Map evidence collection, ownership, and automation to organizational policy. Framework: SOC 2 (TSC Security).
SW360_BODY_soc2_cc9_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
