import { NextResponse } from "next/server";
import { inngest } from "@/inngest/client";
import { requireTenantAccess } from "@/lib/tenant-guard";
import type { InngestEventMap } from "@/types";

const allowedSeverities = ["info", "low", "medium", "high", "critical"] as const;

type SimulateAlertBody = {
  tenantId?: unknown;
  source?: unknown;
  alertType?: unknown;
  severity?: unknown;
  title?: unknown;
  description?: unknown;
  targetValue?: unknown;
  createFinding?: unknown;
};

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
    value
  );
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as SimulateAlertBody;
    const tenantId = typeof body.tenantId === "string" ? body.tenantId.trim() : "";
    if (!tenantId || !isUuid(tenantId)) {
      return NextResponse.json(
        { ok: false, error: "tenantId is required and must be a valid UUID" },
        { status: 400 }
      );
    }

    const guard = await requireTenantAccess({
      tenantId,
      allowedRoles: ["owner", "admin", "analyst"],
    });
    if (!guard.ok) {
      return NextResponse.json({ ok: false, error: guard.error }, { status: guard.status });
    }

    const severity =
      typeof body.severity === "string" ? body.severity.trim().toLowerCase() : "high";
    if (!allowedSeverities.includes(severity as (typeof allowedSeverities)[number])) {
      return NextResponse.json(
        { ok: false, error: `severity must be one of: ${allowedSeverities.join(", ")}` },
        { status: 400 }
      );
    }

    const eventData: InngestEventMap["securewatch/monitoring.alert.received"] = {
      tenantId,
      source: typeof body.source === "string" && body.source.trim() ? body.source.trim() : "simulator",
      alertType:
        typeof body.alertType === "string" && body.alertType.trim()
          ? body.alertType.trim()
          : "suspicious_login",
      severity: severity as InngestEventMap["securewatch/monitoring.alert.received"]["severity"],
      title:
        typeof body.title === "string" && body.title.trim()
          ? body.title.trim()
          : "Simulated monitoring alert",
      description:
        typeof body.description === "string" && body.description.trim()
          ? body.description.trim()
          : "Generated by /api/monitoring/alerts/simulate for workflow testing.",
      targetValue:
        typeof body.targetValue === "string" && body.targetValue.trim()
          ? body.targetValue.trim()
          : "app.securewatch360.local",
      createFinding: typeof body.createFinding === "boolean" ? body.createFinding : undefined,
      metadata: {
        simulated: true,
      },
    };

    const ingest = await inngest.send({
      name: "securewatch/monitoring.alert.received",
      data: eventData,
    });

    return NextResponse.json(
      {
        ok: true,
        message: "Monitoring alert event queued",
        event: {
          name: "securewatch/monitoring.alert.received",
          data: eventData,
        },
        ingest,
      },
      { status: 202 }
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json(
      { ok: false, error: "Failed to simulate monitoring alert", message },
      { status: 500 }
    );
  }
}
