# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_oc_03

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.OC-03"
  value = {
    framework   = "NIST"
    code        = "GV.OC-03"
    title       = <<-SW360_TITLE_nist_gv_oc_03
Legal, regulatory, and contractual requirements regarding cybersecurity - including privacy and civil liberties obligations - are understood and managed
SW360_TITLE_nist_gv_oc_03
    description = <<-SW360_BODY_nist_gv_oc_03
Catalog control GV.OC-03. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_oc_03
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
