# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cmmc_03_06_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CMMC 03.06.05"
  value = {
    framework   = "CMMC"
    code        = "03.06.05"
    title       = <<-SW360_TITLE_cmmc_03_06_05
Incident Response Plan
SW360_TITLE_cmmc_03_06_05
    description = <<-SW360_BODY_cmmc_03_06_05
Catalog control 03.06.05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-171 Rev3 security requirements (CMMC L2 technical practice catalog).
SW360_BODY_cmmc_03_06_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
