# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_ia_7

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP IA-7"
  value = {
    framework   = "FEDRAMP"
    code        = "IA-7"
    title       = <<-SW360_TITLE_fedramp_ia_7
Cryptographic Module Authentication
SW360_TITLE_fedramp_ia_7
    description = <<-SW360_BODY_fedramp_ia_7
Catalog control IA-7. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_ia_7
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
