# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cis_11_5

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "CIS 11.5"
  value = {
    framework   = "CIS"
    code        = "11.5"
    title       = <<-SW360_TITLE_cis_11_5
CIS Controls v8 Safeguard 11.5
SW360_TITLE_cis_11_5
    description = <<-SW360_BODY_cis_11_5
Catalog control 11.5. Map evidence collection, ownership, and automation to organizational policy. Framework: CIS Controls v8.
SW360_BODY_cis_11_5
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
