# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug pci_dss_7_3

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "PCI_DSS 7.3"
  value = {
    framework   = "PCI_DSS"
    code        = "7.3"
    title       = <<-SW360_TITLE_pci_dss_7_3
PCI DSS v4 — Requirement 7.3 (define testing procedures per PCI SSC standard)
SW360_TITLE_pci_dss_7_3
    description = <<-SW360_BODY_pci_dss_7_3
Catalog control 7.3. Map evidence collection, ownership, and automation to organizational policy. Framework: PCI DSS v4.
SW360_BODY_pci_dss_7_3
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
