# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_gv_sc_07

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST GV.SC-07"
  value = {
    framework   = "NIST"
    code        = "GV.SC-07"
    title       = <<-SW360_TITLE_nist_gv_sc_07
The risks posed by a supplier, their products and services, and other third parties are understood, recorded, prioritized, assessed, responded to, and monitored over the course of the relationship
SW360_TITLE_nist_gv_sc_07
    description = <<-SW360_BODY_nist_gv_sc_07
Catalog control GV.SC-07. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_gv_sc_07
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
