# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug soc2_cc7_5

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "SOC2 CC7.5"
  value = {
    framework   = "SOC2"
    code        = "CC7.5"
    title       = <<-SW360_TITLE_soc2_cc7_5
SOC 2 (TSC Security) — CC7.5 (System operations)
SW360_TITLE_soc2_cc7_5
    description = <<-SW360_BODY_soc2_cc7_5
Catalog control CC7.5. Map evidence collection, ownership, and automation to organizational policy. Framework: SOC 2 (TSC Security).
SW360_BODY_soc2_cc7_5
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
