# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_ir_04

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.IR-04"
  value = {
    framework   = "NIST"
    code        = "PR.IR-04"
    title       = <<-SW360_TITLE_nist_pr_ir_04
Adequate resource capacity to ensure availability is maintained
SW360_TITLE_nist_pr_ir_04
    description = <<-SW360_BODY_nist_pr_ir_04
Catalog control PR.IR-04. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_ir_04
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
