# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sr_10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SR-10"
  value = {
    framework   = "FEDRAMP"
    code        = "SR-10"
    title       = <<-SW360_TITLE_fedramp_sr_10
Inspection of Systems or Components
SW360_TITLE_fedramp_sr_10
    description = <<-SW360_BODY_fedramp_sr_10
Catalog control SR-10. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sr_10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
