# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_pr_aa_05

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST PR.AA-05"
  value = {
    framework   = "NIST"
    code        = "PR.AA-05"
    title       = <<-SW360_TITLE_nist_pr_aa_05
Access permissions, entitlements, and authorizations are defined in a policy, managed, enforced, and reviewed, and incorporate the principles of least privilege and separation of duties
SW360_TITLE_nist_pr_aa_05
    description = <<-SW360_BODY_nist_pr_aa_05
Catalog control PR.AA-05. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_pr_aa_05
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
