# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_pl_4_1

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP PL-4.1"
  value = {
    framework   = "FEDRAMP"
    code        = "PL-4.1"
    title       = <<-SW360_TITLE_fedramp_pl_4_1
Social Media and External Site/Application Usage Restrictions
SW360_TITLE_fedramp_pl_4_1
    description = <<-SW360_BODY_fedramp_pl_4_1
Catalog control PL-4.1. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_pl_4_1
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
