# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug cobit_bai10

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "COBIT BAI10"
  value = {
    framework   = "COBIT"
    code        = "BAI10"
    title       = <<-SW360_TITLE_cobit_bai10
COBIT 2019 — BAI10 Managed configuration
SW360_TITLE_cobit_bai10
    description = <<-SW360_BODY_cobit_bai10
Catalog control BAI10. Map evidence collection, ownership, and automation to organizational policy. Framework: COBIT 2019 — core management practices (sample governance catalog).
SW360_BODY_cobit_bai10
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
