# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug gdpr_art_49

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "GDPR Art_49"
  value = {
    framework   = "GDPR"
    code        = "Art_49"
    title       = <<-SW360_TITLE_gdpr_art_49
GDPR Article 49 — Derogations for specific situations
SW360_TITLE_gdpr_art_49
    description = <<-SW360_BODY_gdpr_art_49
Catalog control Art_49. Map evidence collection, ownership, and automation to organizational policy. Framework: EU GDPR (2016/679) — selected articles for operational mapping.
SW360_BODY_gdpr_art_49
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
