# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug nist_rs_an_06

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "NIST RS.AN-06"
  value = {
    framework   = "NIST"
    code        = "RS.AN-06"
    title       = <<-SW360_TITLE_nist_rs_an_06
Actions performed during an investigation are recorded, and the records' integrity and provenance are preserved
SW360_TITLE_nist_rs_an_06
    description = <<-SW360_BODY_nist_rs_an_06
Catalog control RS.AN-06. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST Cybersecurity Framework 2.0.
SW360_BODY_nist_rs_an_06
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
