# Generated by scripts/generate-policy-pack-iac.mjs — catalog slug fedramp_sa_4_9

variable "enforcement_mode" {
  description = "advisory | enforced"
  type        = string
  default     = "advisory"
}

output "securewatch360_control" {
  description = "FEDRAMP SA-4.9"
  value = {
    framework   = "FEDRAMP"
    code        = "SA-4.9"
    title       = <<-SW360_TITLE_fedramp_sa_4_9
Functions, Ports, Protocols, and Services in Use
SW360_TITLE_fedramp_sa_4_9
    description = <<-SW360_BODY_fedramp_sa_4_9
Catalog control SA-4.9. Map evidence collection, ownership, and automation to organizational policy. Framework: NIST SP 800-53 Rev5 MODERATE baseline (FedRAMP-aligned catalog).
SW360_BODY_fedramp_sa_4_9
    version     = 1
    mode        = var.enforcement_mode
    checklist = [
      "Map evidence collection, ownership, and automation to organizational policy",
      "Align automation hooks with SecureWatch360 policy bindings for this catalog control",
    ]
  }
}
